value = input('Type anything: ')

type_value = type(value)
isalnum = value.isalnum()
isalpha = value.isalpha()
isdecimal = value.isdecimal()
isdigit = value.isdigit()
isidentifier = value.isidentifier()
islower = value.islower()
isnumeric = value.isnumeric()
isprintable = value.isprintable()
isspace = value.isspace()
istitle = value.istitle()
isupper = value.isupper()

print()
print('Description about value typed')
print()
print("type: {}".format(type_value))
print("It's an alphanumeric: {}".format(isalnum))
print("It's an alphabetic: {}".format(isalpha))
print("It's a decimal: {}".format(isdecimal))
print("It's a digit: {}".format(isdigit))
print("It's an identifier: {}".format(isidentifier))
print("It's all lower letter: {}".format(islower))
print("It's a numeric: {}".format(isnumeric))
print("It's a printable: {}".format(isprintable))
print("It's a space: {}".format(isspace))
print("It's a title: {}".format(istitle))
print("It's all upper letter: {}".format(isupper))
